apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rh-support-pods-ocpbugs-2474
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
