apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rh-support-pods-ocpbugs-2474
rules:
- verbs:
    - use
  apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  resourceNames:
    - node-exporter